### ISSUE TITLE
Explain the difference between lbry and lbry fdroid

### ISSUE THREAD

**Issue by Thewisem** [lbryio/lbry-fdroid#15]
## The Issue
There is no documentation on the changes made to make it fdroid special
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This repo is just to for the fdroid build process. We'll get this added to the readme.

**Comment by Thewisem** [comment]
You haven't added this in the fdroid repository readme

**Comment by Thewisem** [comment]
Add that

**Comment by kekkyojin** [comment]
This repository, as @tzarebczan explained, is to allow F-Droid to build and publish LBRY on their "store". F-Droid requires apps to no use any closed-source code, i.e. Google's libraries and tracking services.

Any difference between LBRY Android and LBRY FDroid is documented on this repository source code. People using FDroid already know the difference. The app description on their listing doesn't have to explicitly state it as apps over there aren't allowed to use closed-source code.

Over here, as I said, code -which is open source, so it is publicly available- explains the difference in the best possible way. Changes here are commited because of FDroid policies. There could also be changes from Google on the Play Store policies which are not explained on LBRY Android readme file. Changes are always explained on code and on commit messages.

The same would apply to an hypothetical lbry-ios repository. Any difference would be caused by the corresponding policy difference, and the commit message is explaining it. Or what about lbry-android versus lbry-desktop repositories? Differences are always caused by different policies on the store or the operating system it is being coded for.

Adding all of this into the README file would make any harm, but I find it redundant, as LBRY FDroid repository description is already stating that this is the repository for the LBRY app listing on FDroid.

**Comment by Thewisem** [comment]
Not everybody would just come and check source code to see the difference. Not every user of fdroid is a nerd who knows coding. You have to state in the readme the changes you made rather than say that read the code and understand. Plus unlike your examples, this is on a single platform. So there shouldn't be a huge change. And I don't want to know the changes in desktop or ios or any other platform. I only want to know whether this is the same app as play store. If not, what changes were made to make this fdroid available? And you know damn well that lbry users don't all know how to read code. So please don't say that.

**Comment by Thewisem** [comment]
This is the same platfoem not different one

**Comment by alphaonion** [comment]
Just run a hash on the executable.  It should be the same as the one lbry uses.

**Comment by Thewisem** [comment]
So it is the same thing. Could have said that
