### ISSUE TITLE
Incompatible version 

### ISSUE THREAD

**Issue by jneumann** [lbryio/lbry-fdroid#3]
## The Issue
I am unable to install lbry manually or through f droid

### Expected behaviour
Install the app on my phone 

### Actual behaviour
Can't install the app

## System Configuration
- Device: LG stylo g4
- Android version: 9

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
Which version of the app where you trying to install from FDroid?

FDroid is only building 64-bits automatically for new versions. 32 bits have to be added manually, but there is a queue to add them, so most new versions are only available in 64 bits versions. If your device has a 32 bits Android version, you won't be able to install those newest versions.

**Comment by jneumann** [comment]
I'm not sure what version I tried to install from f Droid, it says no versions are compatible.

My kernel architecture is armv7i

**Comment by jneumann** [comment]
I'm not sure what version I tried to install from f Droid, it says no versions are compatible.

My kernel architecture is armv7i

**Comment by kekkyojin** [comment]
> I'm not sure what version I tried to install from f Droid, it says no versions are compatible.

After manually trying to download 0.15.16 for a 32-bits CPU architecture, it seems they have already deleted the APK file. I will ask them to increase the amount of installable packages available. That could make an APK file for your architecture more likely to always be available.

> My kernel architecture is armv7i

That is a 32-bits architecture, and all the available builds on the FDroid repository are 64-bits ones. After each new LBRY FDroid release, I also ask FDroid team to build the 32-bits one, but it has been a long time since they updated their build script. They are volunteers, so there is not too much that can be done except waiting for them to accept the changes which allow the 32 bits one to also be available.

**Comment by kekkyojin** [comment]
Try adding https://f-droid.org/archive to your repositories on the FDroid app. Then, after updating your repositories, there would be available more versions for LBRY. The one you are intersted in would be the one with size 53 MB.

**Comment by TPS** [comment]
@kekkyojin Acknowledging F-droid's shortcomings, most devs work around it either by having F-droid build:
- a fat APK, containing _all_ targeted architectures in 1, & then, on installation, the user's device chooses the correct parts

or
- just the _arm32_ APK, as that's the lowest common denominator, since even arm64 (but not Intel x32/x64) devices can run them

**Comment by kekkyojin** [comment]
Thanks for your suggestions, @TPS. LBRY FDroid will be built only for 32 bits armeabi devices for a while from now until a better solution is found.

A fat APK would not work, as native code is only required for the lbry-android-sdk, which has split AAR files for 32 and 64 bits architectures. As they are in different files, it is not possible to include on a single APK, as gradle build will fail because of the duplicated classes.

**Comment by kekkyojin** [comment]
Check latest update 0.16.6 on FDroid, @jneumann. That's for 32 bits devices. From now on, the app will only be available for these architecture.

Tested on my own smartphone, 64 bits built LBRY app is also able to be updated to this 32 bits one.

**Comment by TPS** [comment]
@kekkyojin Just noticed that the previous versions included _both_ arm64 _&_ x86_64.  Is it possible to include x86_32 _along_ w/ the current arm32 builds?  That would expand the reach of the app, while maintaining maximum compatibility.
