### ISSUE TITLE
F-Droid has google referencing strings

### ISSUE THREAD

**Issue by licaon-kter** [lbryio/lbry-fdroid#6]
APK: https://f-droid.org/repo/io.lbry.browser_16101.apk

Report: https://www.virustotal.com/gui/file/86a478c9b3ebc766677cb055c53558623c519cefe1f15e14ff8e838496cb0f97/details

This usually means there's some non-FOSS dep pulled in at build time.

**Comment by kekkyojin** [comment]
Thank you for creating a bug report here to fix the problem.

After excluding play-services dependencies which were injected from some other dependency, I have been able to remove all Google related strings from the Interesting Strings. See https://www.virustotal.com/gui/file/e8b589076c4c2898a028446fbeb27da1dd1c0e862283b73999b82b17d2274151/details

These dependencies were injected because a helper class imports another helper class from GMS. To remove those strings from FDroid build, it would be needed to remove that import first. I am about to create a new PR on lbry-android which removes that import and replaces it for another one from Apache which does the same job. After it is merged on lbry-android and on lbry-fdroid, I will exclude those play-services dependencies on app/build.gradle.

**Comment by kekkyojin** [comment]
It seems fixed now, @licaon-kter.

https://www.virustotal.com/gui/file/a2af6ebf60f9d93f8882ec518ef497e5af85bc338372b332213a4e6665535fd1/details

Close this issue when you confirm it as fixed.

**Comment by licaon-kter** [comment]
Could you sync translations first or whatever this error says? https://gist.github.com/licaon-kter/b0ca077006edc2c1f2e48a4a2c154d6c

**Comment by licaon-kter** [comment]
I can abortonerror false to bypass that ^^^ and build.

@kekkyojin ok, no more strings...but services? receivers? still `gms` there?
https://www.virustotal.com/gui/file/c85821e921f6c84af2f88a942bd3db9a814c449fe2f8bfa9fe4c9830386f213d/details
